CREATE OR REPLACE FUNCTION capitalize_first_only(value TEXT) RETURNS TEXT AS
  $BODY$
  BEGIN
    RETURN UPPER(SUBSTRING(value FROM 1 FOR 1)) || SUBSTRING(value FROM 2 FOR LENGTH(value));
  END;
  $BODY$
LANGUAGE plpgsql IMMUTABLE;
